### ISSUE TITLE
[ADD] Créer liste de favoris

### ISSUE THREAD

**Issue by andresbrocco** [maxd935/PA-4IWJ-Grp1#27]
- [x] Ajouter attributs "annonces_favoris" et "evenements_favoris" à l'entité user.

Dans le cas ou l'user a fait login:
- [x] Dans la vitrine, ajouter un bouton "favori" pour chaque événement et annonce
- [x] Dans les pages /evenement/show.html.twig et /annonce/show.html.twig ajouter le bouton "favori"
- [x] Créer onglet "Mes favoris" avec une page pareil a vitrine (mes annonces favoris et mes événements favoris) - Créer fichier /templates/favoris/index.html.twig

**Comment by maxd935** [comment]
- [ ] Etat Favori indépendant des profils (problème l'état reste true meme après la déconnexion)
